In [18]:
import pandas as pd
from sqlalchemy import create_engine

# create DB engine (same connection string used in your other notebooks)
engine = create_engine(
    "postgresql://postgres:root@localhost:5432/ecommerce_analytics"
)

In [25]:
orders["order_purchase_timestamp"] = pd.to_datetime(
orders["order_purchase_timestamp"]
)

In [27]:
monthly_sales = orders.groupby(
orders["order_purchase_timestamp"].dt.to_period("M")
)["order_id"].count().reset_index()

In [28]:
monthly_sales.head()

  order_purchase_timestamp  order_id
0                  2016-09         1
1                  2016-10       265
2                  2016-12         1
3                  2017-01       750
4                  2017-02      1653

In [29]:
monthly_sales.columns = ["month","actual_orders"]

In [30]:
monthly_sales.head()

     month  actual_orders
0  2016-09              1
1  2016-10            265
2  2016-12              1
3  2017-01            750
4  2017-02           1653

In [31]:
monthly_sales["forecast_orders"] = monthly_sales["actual_orders"].rolling(3).mean()

In [32]:
monthly_sales.to_csv(
"../data_outputs/sales_forecast.csv",
index=False
)